### ISSUE TITLE
ApexChart's view is not fittting it's parent when I make browser smaller.

### ISSUE THREAD

**Issue by salihyalcin** [salihyalcin/covid19map#6]
Hi, 

When I make the browser smaller, ApexChart is not fitting the actual parent. I would like to explain using a screenshot.  I found a [StackOverflow ](https://stackoverflow.com/questions/64124752/apexchart-width-overflows-or-doesnt-strech)issue that somebody also has the same problem but couldn't able to understand the fixing way. 

![xxx](https://user-images.githubusercontent.com/9201717/140279058-f43a8041-e3bc-4991-8966-adf215b28e3a.png)

**Comment by salihyalcin** [comment]
@israrahmed003 maybe you can look :D

**Comment by israrahmed003** [comment]
@salihyalcin  Issue Resolved
